### ISSUE TITLE
POST request 401

### ISSUE THREAD

**Issue by swirlsnap** [LaurentMT/pybitid_demo#1]
Awesome demo app, getting an 401 error when i attempt to log in via the QR code when serving on my web server -- i can access the demo from the outside world without issue, though. Error:
[17/Oct/2015 17:40:46] "POST /callback?x=43094b6c7deb2c44&u=1 HTTP/1.1" 401 -

 Is this to be expected 0.o

**Comment by LaurentMT** [comment]
Hi @swirlsnap,

HTTP 401 is returned by bitid server when authentication fails. Usually, the causes are:
- the nonce sent in POST request is invalid (not generated by the server)
- the nonce has expired
- the signature is invalid
- the address sent in POST request doesn't match the key used for the signature.
- the address sent in POST request is rejected by the server (e.g: a bitcoin testnet address is expected but a mainnet address has been used to sign the challenge... or the converse)

My best guess is that you may have a problem with the last point (invalid address).

If you use the pybitid demo, note that an address for the bitcoin testnet is expected by default. 
If you want to use an address for the bitcoin main network, you just have to edit line 26 of file pybitid_demo.py and replace
USE_TESTNET = True
by
USE_TESTNET = False

Hope it helps.
laurent

Edit: The body of the response returned by the server should embed a small json with details about the problem encountered. That may be useful to debug the problem ! :)

**Comment by swirlsnap** [comment]
Helps a lot, thank you :+1: It's all working now.
